### ISSUE TITLE
One liner install error in UI

### ISSUE THREAD

**Issue by venkat-oss** [InseeFrLab/onyxia#820]
Followed the one liner installation on a kubernetes cluster. This worked in a previous version of onyxia.
But now I see this error in the developer console. web ui is stuck at loading view.

createObjectThatThrowsIfAccessed.js:49 Uncaught (in promise) Error: Cannot access Symbol(immer-state) yet You haven't provided a mocked decodedIdToken
See https://docs.oidc-spa.dev/documentation/mock
    at new i (createObjectThatThrowsIfAccessed.js:49:28)
    at Object.a (createObjectThatThrowsIfAccessed.js:70:15)
    at r (immer.esm.mjs:1:425)
    at A (immer.esm.mjs:1:3107)
    at immer.esm.mjs:1:2742
    at immer.esm.mjs:1:948
    at Array.forEach (<anonymous>)
    at i (immer.esm.mjs:1:904)
    at M (immer.esm.mjs:1:2716)
    at P (immer.esm.mjs:1:2548)

![image](https://github.com/InseeFrLab/onyxia/assets/9056253/17058f99-af07-4262-b291-4c149f6c7447)

Thank you for looking into this.

**Comment by garronej** [comment]
thank you for reporting I'll address now

**Comment by garronej** [comment]
A new version is being deployed. Sony for the inconvenience.
